# Generated by Django 5.0 on 2025-05-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('raw', models.TextField(blank=True)),
                ('regexp_source', models.TextField(blank=True)),
                ('regexp_flag', models.CharField(blank=True, max_length=20)),
                ('replace_value', models.JSONField(blank=True, default=dict)),
                ('groups', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('memo', models.TextField(blank=True)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TranslationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=255)),
                ('content', models.TextField()),
                ('content_hash', models.CharField(editable=False, max_length=32)),
            ],
            options={
                'verbose_name': 'Translation data',
                'verbose_name_plural': 'Translation data',
            },
        ),
        migrations.AddConstraint(
            model_name='matcher',
            constraint=models.UniqueConstraint(condition=models.Q(('raw', ''), _negated=True), fields=('category', 'raw',), name='uniq_raw_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='matcher',
            constraint=models.UniqueConstraint(condition=models.Q(('raw', '')), fields=('category', 'raw', 'regexp_source', 'regexp_flag'), name='uniq_regex_pair'),
        ),
        migrations.AddConstraint(
            model_name='translationdata',
            constraint=models.UniqueConstraint(fields=('source', 'content_hash'), name='uniq_source_hash'),
        ),
    ]
