# Generated by Django 5.0 on 2025-05-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('raw', models.TextField(blank=True)),
                ('regexp_source', models.TextField(blank=True)),
                ('regexp_flag', models.CharField(blank=True, max_length=20)),
                ('replace_value', models.JSONField(blank=True, default=dict)),
                ('groups', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
