# Generated by Django 5.2 on 2025-05-02 XX:XX
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matcher",
            name="memo",
            field=models.TextField(blank=True),
        ),
    ]
