# Generated by Django 5.0 on 2025-05-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=255)),
                ('content', models.TextField()),
            ],
            options={
                'unique_together': {('source', 'content')},
            },
        ),
    ]
