{
 "title": "CNC Server Status",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Connections",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "session_data{type=\"total\"}",
     "legendFormat": "Number of connections"
    },
    {
     "expr": "session_data{type=\"playing\"}",
     "legendFormat": "Number of playing sessions"
    },
    {
     "expr": "session_data{type=\"watching\"}",
     "legendFormat": "Number of watching sessions"
    },
    {
     "expr": "session_data{type=\"lobby\"}",
     "legendFormat": "Number of lobby sessions"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "session_data{type=\"total\"}",
     "legendFormat": "Number of connections"
    },
    {
     "expr": "session_data{type=\"playing\"}",
     "legendFormat": "Number of playing sessions"
    },
    {
     "expr": "session_data{type=\"watching\"}",
     "legendFormat": "Number of watching sessions"
    },
    {
     "expr": "session_data{type=\"lobby\"}",
     "legendFormat": "Number of lobby sessions"
    }
   ]
  },
  {
   "title": "Server Latency",
   "type": "timeseries",
   "description": "Gyeonggi (CNC) to Chuncheon (OCI) in Korea",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "latency", "legendFormat": "Latency" }
   ]
  },
  {
   "title": "Playing sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "session_data{type=\"playing\"}",
     "legendFormat": "Number of playing sessions"
    },
    {
     "expr": "session_data{type=\"playing_idle\"}",
     "legendFormat": "Number of idle playing sessions"
    }
   ]
  },
  {
   "title": "Watching sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "session_data{type=\"watching\"}",
     "legendFormat": "Number of watching sessions"
    },
    {
     "expr": "session_data{type=\"watching_anon\"}",
     "legendFormat": "Number of anon watching sessions"
    }
   ]
  },
  {
   "title": "Lobby sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "session_data{type=\"lobby\"}",
     "legendFormat": "Number of lobby sessions"
    }
   ]
  }
 ]
}