# Generated by Django 5.2 on 2025-04-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('raw', models.TextField(blank=True, null=True)),
                ('regex', models.TextField(blank=True, null=True)),
                ('regexp_source', models.TextField(blank=True, null=True)),
                ('regexp_flag', models.CharField(blank=True, max_length=20, null=True)),
                ('replace_value', models.TextField()),
                ('groups', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '매처',
                'verbose_name_plural': '매처 목록',
            },
        ),
        migrations.CreateModel(
            name='TranslationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=255)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': '원문',
                'verbose_name_plural': '원문 목록',
                'unique_together': {('source', 'content')},
            },
        ),
    ]
